import { StyleSheet, Dimensions } from 'react-native';
import { colors } from './colors';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const isSmallScreen = SCREEN_WIDTH < 400;
const isLargeScreen = SCREEN_WIDTH > 900;

export const headerStyles = StyleSheet.create({
  header: {
    width: '100%',
    maxWidth: isLargeScreen ? 1800 : isSmallScreen ? 600 : 1400,
    marginLeft: 'auto',
    marginRight: 'auto',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: isSmallScreen ? 12 : isLargeScreen ? 20 : 16,
    paddingBottom: isSmallScreen ? 8 : isLargeScreen ? 20 : 12,
    paddingHorizontal: isSmallScreen ? 12 : isLargeScreen ? 64 : 32,
    backgroundColor: colors.branco,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(109, 76, 65, 0.2)',
    shadowColor: colors.marromFeijao,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    boxSizing: 'border-box',
    position: 'relative',
    zIndex: 9999,
  },
  logo: {
    fontSize: isSmallScreen ? 16 : isLargeScreen ? 40 : 32, // Ainda mais reduzido para mobile
    fontWeight: 'bold',
    color: colors.verdeFolha,
    letterSpacing: 1,
  },
  actions: {
    flexDirection: 'row',
    gap: isSmallScreen ? 6 : 16,
    flexWrap: 'wrap',
    justifyContent: isSmallScreen ? 'center' : 'flex-end',
    flexShrink: 1,
    maxWidth: '100%',
  },
  btn: {
    paddingVertical: isSmallScreen ? 6 : 10,
    paddingHorizontal: isSmallScreen ? 14 : 20,
    fontSize: isSmallScreen ? 13 : 15,
    color: colors.verdeFolha,
    backgroundColor: colors.branco,
    borderRadius: 10,
    fontWeight: '600',
    borderWidth: 2,
    borderColor: colors.verdeFolha,
    marginLeft: isSmallScreen ? 6 : 10,
    shadowColor: colors.verdeFolha,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  btnActive: {
    borderWidth: 2,
    borderColor: colors.verdeFolha,
    backgroundColor: colors.verdeFolha,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  btnRegister: {
    backgroundColor: colors.vermelhoCambuci,
    color: colors.branco,
    fontWeight: '600',
    borderColor: colors.vermelhoCambuci,
    borderWidth: 1.5,
  },
  cartButton: {
    position: 'relative',
    paddingVertical: isSmallScreen ? 8 : 10,
    paddingHorizontal: isSmallScreen ? 12 : 16,
    backgroundColor: 'transparent',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: isSmallScreen ? 6 : 10,
    minWidth: isSmallScreen ? 40 : 48,
    minHeight: isSmallScreen ? 40 : 48,
  },
  cartBadge: {
    position: 'absolute',
    top: isSmallScreen ? -4 : -6,
    right: isSmallScreen ? -4 : -6,
    backgroundColor: colors.vermelhoCambuci,
    borderRadius: 12,
    minWidth: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2.5,
    borderColor: colors.branco,
    shadowColor: colors.preto,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  cartBadgeText: {
    color: colors.branco,
    fontSize: isSmallScreen ? 11 : 13,
    fontWeight: '800',
  },
  // Menu suspenso (usado inline, mas pode ser referenciado)
  dropdownMenu: {
    backgroundColor: colors.branco,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.marromFeijao,
    minWidth: 180,
    zIndex: 9999,
    shadowColor: colors.marromFeijao,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
  },
  mobileMenuPanel: {
    width: '100%',
    backgroundColor: colors.branco,
    borderBottomWidth: 1,
    borderBottomColor: colors.marromFeijao,
    borderTopWidth: 0,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  mobileMenuItem: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.marromFeijao,
  },
  mobileMenuText: {
    color: colors.verdeFolha,
    fontWeight: 'bold',
    fontSize: 16,
  },
}); 